version: "2.2"
services:
  app:
      container_name: app
      restart: always
      build: ./
      ports:           
        - "4005:4005"
      depends_on:
        - mongo
  client:
      container_name: client
      restart: always
      build: ./client
      ports:
        - "3000:3000"
      depends_on:
        - app
  mongo:
      container_name: mongo
      restart: always
      image: mongo
      ports:
        - "27017:27017"